# Generated by Django 5.1.7 on 2025-03-14 20:13

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('category', models.CharField(choices=[('Fiction', 'FICTION'), ('Science', 'SCIENCE'), ('History', 'HISTORY')], max_length=100)),
                ('copies', models.IntegerField()),
            ],
        ),
    ]
