# Generated by Django 5.1.7 on 2025-03-18 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0003_borrows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='category',
            field=models.CharField(choices=[('Fiction', 'FICTION'), ('Science', 'SCIENCE'), ('History', 'HISTORY'), ('Technology', 'TECHNOLOGY'), ('Romantic', 'ROMANTIC'), ('Adventure', 'ADVENTURE')], max_length=100),
        ),
    ]
