# Generated by Django 5.1.7 on 2025-03-18 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0004_alter_books_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Borrows',
        ),
    ]
